//Login
export const CHANGE_LOGIN_USERNAME = 'CHANGE_LOGIN_USERNAME'
export const CHANGE_LOGIN_PASSWORD = 'CHANGE_LOGIN_PASSWORD'

//Register
export const CHANGE_REGISTER_USERNAME = 'CHANGE_REGISTER_USERNAME'
export const CHANGE_REGISTER_PASSWORD = 'CHANGE_REGISTER_PASSWORD'
export const CHANGE_NAME = 'CHANGE_NAME'
export const CHANGE_LASTNAME = 'CHANGE_LASTNAME'
export const CHANGE_BIRTHDAY = 'CHANGE_BIRTHDAY'
export const CHANGE_EMAIL = 'CHANGE_EMAIL'
